### ISSUE TITLE
При отключении публичной ссылки не удаляется post_name записи

### ISSUE THREAD

**Issue by campusboy87** [mihdan/mihdan-public-post-preview#4]
При удалении галки "Публичная ссылка" в метабоксе плагина мне, как автору, всегда была доступна по этой самой прямой ссылке запись-черновик. Я подумал, что дело в галке (баг в обновлении ajax), оказалось нет. WordPress работает следующим образом (без плагина):
* У черновик `нет post_name` - "авторизованному" и гостю по прямой ссылке отдаст 404
* У черновика `есть post_name` - "авторизованному" по прямой ссылке отдаст 200, а гостю - 404. Это поведение меня и сбило, я подумал плагин "моросит" и запись остаётся доступной навсегда, пока включён плагин.

В любом случае, плагин должен удалять post_name при "выключении" галки, в коде это якобы есть:
```
// Удалим post_name у записи. Важно!!!
$args = array(
    'ID'        => $post->ID,
    'post_name' => '',
);

wp_update_post( $args );

// Удалим мету
delete_post_meta( $post_id, self::META_NAME );
```

Но в силу порядка выполнения кода происходит следующее по порядку:
1) При выполнении wp_update_post() -> wp_insert_post() в post_name записывается пустая строка.
2) В конце этого процесса рабатывает хук wp_insert_post и  в коллбеке плагина fix_post_name идёт проверка `$this->is_post_previewable( $post )`, которая в свою очередь проверяет мету, в которой есть 1, так она ещё не удалена, что даёт положительный результат и код обновляет post_name на основе post_title, то есть **post_name возвращается на место**!
3) Удаляется мета с 1, хотя уже поздно для процесс из 2 пункта.

То есть процесс должен идти наоборот:
```
// Удалим мету
delete_post_meta( $post_id, self::META_NAME );

// Удалим post_name у записи. Важно!!!
$args = array(
    'ID'        => $post->ID,
    'post_name' => '',
);

wp_update_post( $args );
```

**Comment by campusboy87** [comment]
Чуток запутался, прошу прощения. Проблема оказалась в чем - я думал, что дело в галке, оказалось нет. WordPress работает следующим образом (без плагина):
* У черновик `нет post_name` - "авторизованному" и гостю по прямой ссылке отдаст 404
* У черновика `есть post_name` - "авторизованному" по прямой ссылке отдаст 200, а гостю - 404. Это поведение меня и сбило, я подумал плагин "моросит" и запись остаётся доступной навсегда, пока включён плагин.

В любом случае, плагин должен удалять post_name при "выключении" галки, в коде это якобы есть:
```
// Удалим post_name у записи. Важно!!!
$args = array(
    'ID'        => $post->ID,
    'post_name' => '',
);

wp_update_post( $args );

// Удалим мету
delete_post_meta( $post_id, self::META_NAME );
```

Но в силу порядка выполнения кода происходит следующее по порядку:
1) При обновлении записи срабатывает хук wp_insert_post и  в коллбеке плагина fix_post_name идёт проверка `$this->is_post_previewable( $post )`, которая в свою очередь проверяет мету, в которой есть 1, так она ещё не удалена
2) Удаляется мета с 1, хотя уже поздно для процесс из 1 пункта.

То есть процесс должен идти наоборот:
```
// Удалим мету
delete_post_meta( $post_id, self::META_NAME );

// Удалим post_name у записи. Важно!!!
$args = array(
    'ID'        => $post->ID,
    'post_name' => '',
);

wp_update_post( $args );
```

**Comment by mihdan** [comment]
https://github.com/mihdan/mihdan-public-post-preview/pull/5/commits/389af3d4c814d75c3588905addc2e06728cc9155
