### ISSUE TITLE
Ввести проверку на права пользователя

### ISSUE THREAD

**Issue by Otshelnik-Fm** [mihdan/mihdan-public-post-preview#6]
https://github.com/mihdan/mihdan-public-post-preview/blob/1dfd4a5d924bec82b8fc1431a10fcb3e1fddb7da/mihdan-public-post-preview.php#L311
залогиненный может изменить состояние любой записи выставив мету mppp - изменив публичность

**Comment by mihdan** [comment]
TODO: Нужно добавить проверку прав пользователя и nonce

**Comment by mihdan** [comment]
https://github.com/mihdan/mihdan-public-post-preview/commit/b77c4cbba60cb024a974ab65e333af7ab4eda3ab
